version: "3.2"
services:

  install:
    build: .
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    entrypoint: ["npm", "install", "--no-bin-links", "--dev"]

  crawler:
    build: .
    tty: true
    stdin_open: true
    entrypoint: ["ts-node", "./src/main"]
    env_file:
      - .env
    volumes:
      - ./:/app

  tests:
    build: .
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    entrypoint: ["npm", "run", "tests"]

  tests-with-cover:
    build: .
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    entrypoint: ["npm", "run", "tests:cover"]

  shell:
    build: .
    tty: true
    entrypoint: ["/bin/bash"]
    working_dir: "/app"
    volumes:
      - .:/app